#!/bin/sh
case "$2" in
    up)
        tz="$(curl --fail --silent --max-time 5 https://ipapi.co/timezone)"
        if [ -n "$tz" ] && timedatectl list-timezones | grep -qFx "$tz"; then
            timedatectl set-timezone "$tz"
        fi
    ;;
esac

