add_newline = false
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$nodejs\
$python\
$rust\
$memory_usage\
$custom\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time \
$status\
$character\
"""

[username]
format = "[$user]($style)@"
show_always = true

[hostname]
ssh_only = false

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = "שׂ "
disabled = false

[git_commit]
only_detached = false
tag_disabled = false

[git_state]
disabled = false

[git_metrics]
disabled = false

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[docker_context]
symbol = " "
disabled=false

[package]
symbol = " "
disabled = false

[nodejs]
symbol = " "
disabled = false

[python]
symbol = " "
disabled = false

[rust]
symbol = " "
disabled = false

[memory_usage]
symbol = " "
threshold = 75
disabled = false

[cmd_duration]
min_time = 500
show_notifications = true
min_time_to_notify = 30000

[line_break]
# if true info and prompts are merged into a single line
disabled = false

[jobs]

[battery]
disabled = false

[[battery.display]]
threshold = 25
style = "bold red"

[[battery.display]]
threshold = 50
style = "bold yellow"

[[battery.display]]
threshold = 90
style = "bold green"

[time]
format = '[$time]($style)'
time_format = "%T"
disabled = false
style = "blue"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

