# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Do not add a blank line between shell prompts
add_newline = false

# Define the prompt format
format = """
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$aws\
$azure\
$kubernetes\
$docker_context\
$container\
$package\
$nodejs\
$python\
$rlang\
$rust\
$memory_usage\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time \
$sudo\
$character\
"""

[username]
format = "[$user]($style)@"
show_always = true

[hostname]
format = "[$ssh_symbol$hostname]($style)"
ssh_only = false
ssh_symbol = "󰒍 "

[localip]
format = '[\($localipv4\)]($style) in '
ssh_only = false
style = "dimmed green"
disabled = false

[directory]
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true
repo_root_style = "bold yellow"
read_only = " 󰌾"

[git_branch]
symbol = "󰘬 "
disabled = false

[git_commit]
only_detached = false
tag_disabled = false
tag_symbol = " 󰓹 "
style = "purple"

[git_state]
disabled = false
rebase = " REBASING"
merge = "󰘭 MERGING"
revert = "󰌑 REVERTING"
cherry_pick = " CHERRY-PICKING"
bisect = "󰆐 BISECTING"
am = "󰶍 APPLYING MAILBOX"
style = "bold red"

[git_metrics]
disabled = false
format = "([+$added]($added_style):)([-$deleted]($deleted_style) )"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = "(󰞋${count})"
ahead = "( 󰛃${count})"
behind = "( 󰛀${count})"
diverged = "([ 󰀧${ahead_count}:${behind_count}](red bold))"
up_to_date = ""
untracked = "([ 󰅗${count}](green))"
stashed = "([ 󱥬${count}](grey))"
modified = "([ 󱗜${count}](yellow))"
staged = "([ 󰐖${count}](green))"
renamed = "([ 󰛂${count}](yellow))"
deleted = "([ 󰍵${count}](cyan))"
typechanged = ""
style = "purple"

[aws]
format = 'on [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
symbol = "☁️ "
disabled = true

[azure]
format = "on aws [$symbol($username @ $subscription)]($style) "
symbol = "󰠅 "
disabled = false

[kubernetes]
format = "on [$symbol$namespace]($style) "
symbol = "󱃾 "
disabled = false

[docker_context]
symbol = "󰡨 "
disabled = false

[container]
symbol = "󰆧 "
disabled = true

[package]
symbol = "󰏗 "
display_private = true
disabled = false

[nodejs]
symbol = "󰎙 "
disabled = false

[python]
symbol = "󰌠 "
python_binary = ['./.venv/bin/python', 'python', 'python3', 'python2']
disabled = false

[rlang]
symbol = "󰟔 "
disabled = false

[rust]
symbol = "󱘗 "
disabled = false

[memory_usage]
symbol = "󰍛 "
threshold = 75
disabled = false

[cmd_duration]
min_time = 1000
show_notifications = false
# min_time_to_notify = 30000

[line_break]
# if true info and prompts are merged into a single line
disabled = false

[jobs]
symbol = "+ "
number_threshold = 1
disabled = false

[battery]
disabled = false
full_symbol = '󰁹 '
charging_symbol = '󰂄 '
discharging_symbol = '󰁾 '
empty_symbol = '󰁺 '
unknown_symbol = '󰂑 '

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]
threshold = 70
style = "bold yellow"

[[battery.display]]
threshold = 90
style = "bold green"

[time]
format = '[$time]($style)'
time_format = "%T"
disabled = false
style = "blue"

[sudo]
symbol = "󱥠 "
style = "bold red"
disabled = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
