[UPower]
EnableWattsUpPro=false
NoPollBatteries=false
IgnoreLid=false
UsePercentageForPolicy=true
PercentageLow=20.0
PercentageCritical=5.0
PercentageAction=1.0
TimeLow=1200
TimeCritical=300
TimeAction=120
AllowRiskyCriticalPowerAction=false
ExpectBatteryRecalibration=false
CriticalPowerAction=Hibernate
